version: '1.0'
services:
  speech-recognition:
    image: smart-assistant/speech-recognition
    ports:
      - 8080:8080
    volumes:
      - ${SPEECH_RECOGNITION_MODEL}:/models/${WHISPER_MODEL_NAME}
    environment:
      - MODEL_NAME=${WHISPER_MODEL_NAME}
      
  chatbot:
    image: smart-assistant/chatbot
    ports:
      - 8181:8181
    volumes:
      - ${CHATBOT_MODEL}:/models/${CHATBOT_MODEL_NAME}
    environment:
      - MODEL_NAME=${CHATBOT_MODEL_NAME}

  embeddings:
    image: smart-assistant/embeddings
    ports:
      - 8282:8282
    volumes:
      - ${EMBEDDINGS_MODEL}:/models/${EMBEDDINGS_MODEL_NAME}
    environment:
      - MODEL_NAME=${EMBEDDINGS_MODEL_NAME}